spring:
  profiles:
    active: dev
  application:
    name: smart-home-syst
---
spring:
    config:
        activate:
            on profile: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/smart-home-syst
        username: postgres
        password: 2252
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
server:
    port: 8080
---
spring:
    config:
        activate:
            on profile: production
server:
    port: 9001