spring:
  profiles:
    active: dev
  application:
    name: smart-home-syst
---
spring:
    config:
        activate:
            on profile: dev
server:
    port: 8080
---
spring:
    config:
        activate:
            on profile: production
server:
    port: 9001