spring:
  profiles:
    active: dev
  application:
    name: smart-home-syst
---
spring:
    config:
        activate:
            on profile: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/smart-home-syst
        username: postgres
        password: 2252
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
server:
    port: 8080
---
spring:
    config:
        activate:
            on profile: production
server:
    port: 9001
---
jwt:
    secret: b8c3e20c245fe71c330750ca0140c81f0a5982725877c35f890eb92d8f3e568e
    access:
        duration:
            minutes: 5
            second: 300
        cookie-name: access-token
    refresh:
        duration:
            days: 7
            second: 604800
        cookie-name: refresh-token
---
logging:
    level:
        root: INFO
        com.example.smart_home_syst: DEBUG  # Детальные логи
        org.springframework: WARN # Меньше шума от Spring
        org.hibernate: INFO  
    file:
        name: logs/smart-home-syst.log
        max-size: 10MB
        max-history: 30
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %cyan(%logger{36}) - %level - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"
---
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    xml:
      indent-output: true